.PHONY: clean, compile, manual, display, list

compile: tc_data.py tc_time.py tc_handler.py tc_print.py tc_display.py tc_meta.py
	@echo 'compile with python 3'
	@python3 tc_data.py
	@python3 tc_time.py
	@python3 tc_handler.py
	@python3 tc_print.py
	@python3 tc_display.py
	@python3 tc_meta.py
	@echo 'compile with python 2'
	@python  tc_data.py
	@python  tc_time.py
	@python  tc_handler.py
	@python  tc_print.py
	@python  tc_display.py
	@python  tc_meta.py
	make clean

clean:
	rm -rf __pycache__
	rm -rf *.pyc
	rm -rf *test*

manual:
	python3
	make clean

display: tc_display.py
	@touch test_display.py
	@echo '# This file is auto-generated by Makefile.' >> test_display.py
	@echo 'from tc_display import *' >> test_display.py
	@echo 'calendar = make_display()' >> test_display.py
	@echo 'for s in calendar:' >> test_display.py
	@echo '    print (s)' >> test_display.py
	@python3 test_display.py
	make clean

list: tc_user_data.py
	@touch test_list.py
	@echo '# This file is auto-generated by Makefile.' >> test_list.py
	@echo 'from tc_user_data import *' >> test_list.py
	@echo 'print ("\u001b[37;1mTesting List Min\u001b[0m")' >> test_list.py
	@echo 'E = tcl_list_min ()' >> test_list.py
	@echo 'for s in E:' >> test_list.py
	@echo '    print (s)' >> test_list.py
	@echo 'print ("\u001b[37;1mTesting List All\u001b[0m")' >> test_list.py
	@echo 'E = tcl_list_all ()' >> test_list.py
	@echo 'for s in E:' >> test_list.py
	@echo '    print (s)' >> test_list.py
	@python3 test_list.py
	make clean

